[book]
title = "Rspack Development Guide"
authors = ["https://github.com/web-infra-dev/rspack-dev-guide/graphs/contributors"]
language = "en"
multilingual = false
src = "src"

[output.html]

[output.linkcheck]
