[book]
title = "Rspack Development Guide"
authors = ["https://github.com/web-infra-dev/rspack-dev-guide/graphs/contributors"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]

[output.html.search]
use-boolean-and = true

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
