[book]
title = "Rspack Development Guide"
authors = ["https://github.com/web-infra-dev/rspack-dev-guide/graphs/contributors"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]

[output.linkcheck]
